title: Ege Korkan
description: > # this means to ignore newlines until "baseurl:"
  Personal website for information on me, my projects, blog and contact info
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://egekorkan.com" # the base hostname & protocol for your site, e.g. http://example.com
#permalink: ':title/'
blog_theme: light # Or use dark

# Profile information
name: Ege Korkan
tagline: Research Associate
about-description: Researcher at Technical University of Munich working on the Web of Things standards of World Wide Web Consortium
pic: myPic.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: egekorkan@gmail.com # Add your Email address
phone: +49 176 3012 6942 # Add your Phone number
website: https://www.esi.ei.tum.de/en/staff/korkan/ # Add your website, do not add http://
linkedin: ege-korkan # Add your Linkedin handle
github: egekorkan # Add your Github handle
twitter: 'egekorkan' # Add your Twitter handle
xing: Ege_KORKAN
researchgate: Ege_Korkan

# Tracker
analytics: UA-127312090-2

# Comments
discus-identifier: egekorkan # Add your Disqus identifier

# Important settings
assets: 
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets
    - assets/bibtexs

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
